name: Validar Sintaxe do Arquivo de Alertas

on:
  push:
    branches:
    - '*'

env:
  PROMETHEUS_VERSION: '2.43.1'

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: pip install pyyaml regex


    - name: Verificar diretorio
      run: ls -lha
    - name: Instalar promtool
      run: |
        wget https://github.com/prometheus/prometheus/releases/latest/download/prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64.tar.gz
        tar -xvf prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64.tar.gz
        sudo cp prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64/promtool /usr/local/bin/

    - name: Validar sintaxe do arquivo de alertas com promtool
      run: find . -type f -name "*.yaml" -o -name "*.yml" -exec promtool check rules {} +

    - name: Executar validação de sintaxe com Python
      run: python validate_alerts.py
