name: Validar Sintaxe do Arquivo de Alertas

on:
  push:
    branches:
    - '*'

env:
  PROMETHEUS_VERSION: '2.50.1'

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: pip install pyyaml regex

    - name: Instalar promtool
      run: |
        wget https://github.com/prometheus/prometheus/releases/latest/download/prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64.tar.gz
        tar -xvf prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64.tar.gz
        sudo cp prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64/promtool /usr/local/bin/
        rm -fr prometheus-${{ env.PROMETHEUS_VERSION }}.linux-amd64

    - name: Validar sintaxe do arquivo de alertas com o promtool
      run: |
        for dir in *-dev *-hom *-pro; do
          if [[ -d $dir ]]; then
            find "$dir" -type f \( -name "*.yaml" -o -name "*.yml" \) -exec promtool check rules {} +
          fi
        done

    - name: Executar validação de sintaxe com Python
      run: python .github/workflows/validate_alerts.py

    - name: Instala dependências
      run: python -m pip install --upgrade pip

    # - name: Checkout code
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0 # Garante o fetch de todo o histórico

    # - name: Verificar 'email_router' apenas nas linhas adicionadas
    #   run: |
    #     # Obter diferenças do último commit, filtrando por linhas que começam com "+", excluindo as que são parte do cabeçalho do diff
    #     ADDED_LINES=$(git diff HEAD~1 HEAD --unified=0| grep '^+' | grep -v '^+++')
    #     echo "$ADDED_LINES"

    #     # Verificar se as linhas adicionadas contêm o termo 'email_router'
    #     if echo "$ADDED_LINES" | grep -q 'email_router'; then
    #       echo "O termo email_router foi encontrado, por favor remover pois esta descontinuado."
    #       exit 1
    #     else
    #       echo "Nenhum termo 'email_router' encontrado nas linhas adicionadas."
    #     fi

    - name: Procurar 'email_router' nas adições do último commit
      run: |
        # Exibe as mudanças do último commit, filtrando para incluir apenas adições
        # Filtra fora linhas de cabeçalho de arquivo e captura apenas adições reais de código
        ADDED_LINES=$(git show --pretty="format:" --unified=0 HEAD | grep '^\+' | grep -v '^+++' | sed 's/^+//')

        # Verifica se as linhas adicionadas contêm o termo 'email_router'
        if echo "$ADDED_LINES" | grep -q 'email_router'; then
          echo "::error::Termo 'email_router' encontrado nas adições do último commit, por favor remover pois esta descontinuado."
          exit 1
        else
          echo "Nenhum termo 'email_router' encontrado nas adições do último commit."
        fi
